version: '2'

services:
  app:
    image: 'benford:latest'
    build:
      context: ""
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - pg
      - mongo
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://pg:5432/compose-postgres
      - SPRING_R2DBC_USERNAME=compose-postgres
      - SPRING_R2DBC_PASSWORD=compose-postgres
#      - SPRING_DATA_MONGODB_URI=mongodb://mg:27017/compose-mongo
#      - SPRING_DATA_USERNAME=compose-mongo
#      - SPRING_DATA_PASSWORD=compose-mongo


  pg:
    image: 'postgres:14.0'
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql

#  mg:
#    image: 'mongo:5.0.3'
#    container_name: mongo
#    ports:
#      - "27017:27017"
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=compose-mongo
#      - MONGO_INITDB_ROOT_PASSWORD=compose-mongo